[project]
authors = ["Rui Yi Zhang <squirreljetpacks@gmail.com>"]
channels = ["conda-forge"]
description = "Add a short description here"
name = "torch-nibs"
platforms = ["linux-64"]
version = "0.0.4"

[environments]
# test = {features = ["test"], solve-group = "default"}
# docs = {features = ["docs"], solve-group = "default"}
default = {features = [], solve-group = "default"}
dev = {features = ["dev"], solve-group = "default"}

# dev
[feature.dev.dependencies]
pytest = "*"

[feature.dev.pypi-dependencies]
torch-nibs = { path = ".", editable = true}

[feature.dev.system-requirements]
cuda = "12.6"


[dependencies]
# Model
pytorch = "*"
torchvision = "*"
torchaudio = "*"

# Data
polars = "*"
pandas = "*"
# datasets = { version = ">=3.2.0,<4", channel = "huggingface" }

# Training
wandb = "*"

# Docs
jupyter = "*"
pip = "*"
ipympl = "*"

# plotting
plotly = "*"
tqdm = "*"
seaborn = ">=0.13.2,<0.14"
scikit-learn = ">=1.5.2,<2"
# openpyxl = ">=3.1.5,<4"
# fastexcel = ">=0.12.0,<0.13"

[pypi-dependencies]
torcheval = ">=0.0.7,<0.0.8"
