[project]
authors = ["Rui Yi Zhang <squirreljetpacks@gmail.com>"]
channels = ["conda-forge"]
description = "Add a short description here"
name = "torch_nib"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[pypi-dependencies]
torcheval = ">=0.0.7,<0.0.8"

[environments]
# test = {features = ["test"], solve-group = "default"}
# docs = {features = ["docs"], solve-group = "default"}
default = {features = [], solve-group = "default"}
dev = {features = ["dev"], solve-group = "default"}

[feature.dev.dependencies]
pytest = "*"
hatch = ">=1.14.0,<2"
twine = ">=6.0.1,<7"

[dependencies]
# Model
pytorch = "*"
torchvision = "*"
torchaudio = "*"

# Data
polars = "*"

# Training
wandb = "*"

# Docs
jupyter = "*"
pip = "*"
ipympl = "*"

plotly = "*"
tqdm = "*"
seaborn = ">=0.13.2,<0.14"
scikit-learn = ">=1.5.2,<2"
openpyxl = ">=3.1.5,<4"
fastexcel = ">=0.12.0,<0.13"
pandas = ">=2.2.3,<3"
# datasets = { version = ">=3.2.0,<4", channel = "huggingface" }
jupyter_console = ">=6.6.3,<7"

# langchain-openai = { version = ">=0.1.25,<0.2", channel = "conda-forge" }
